### ISSUE TITLE
Add the Binary information to the README 

### ISSUE THREAD

**Issue by Angelmmiguel** [Angelmmiguel/svgi#17]
I'm providing binary files in every [release](https://github.com/Angelmmiguel/svgi/releases/tag/v1.1.0). The README file already includes a section that [mentions the binaries](https://github.com/Angelmmiguel/svgi#node-version), so it must be updated too.

**Comment by shindakun** [comment]
@Angelmmiguel went with a link to the main releases page rather then a link to each released bin, that way the readme doesn't need to be updated in multiple spots on every release. Hope that helps.

**Comment by Angelmmiguel** [comment]
Great!! 

Thank you for the PR @shindakun and happy Hacktoberfest :)
