### ISSUE TITLE
Read stdin

### ISSUE THREAD

**Issue by Angelmmiguel** [Angelmmiguel/svgi#6]
Currently, the CLI get the filename from an argument. It would be nice to read the input from stdin and process it as a normal SVG file:

```
cat myfile.svg | svgi
```

**Comment by JoshuaAF** [comment]
Hey noticed this issue still wasn't closed. Figured out how to deal with stdin but had a few questions.

1. Do you want to replace filename input or just add stdin as an alternative?

2. Are you okay with removing `Name` and `Path` from `Basic Information`? Because those fields don't really make sense if you accept an svg from stdin.

**Comment by Angelmmiguel** [comment]
Hello @JoshuaAF,

Sorry for the delay, I was on holidays. Regarding to your questions:

1. The purpose of this issue is to add `STDIN` as an alternative.
2. It's fine to remove it if the data has been passed through `STDIN`

Thank you for invest some time adding this feature to `svgi`! Happy #hacktoberfest :)

**Comment by JoshuaAF** [comment]
Alright, I'll get started. I'm going to add an optional `--stdin` flag to allow the user to specify that the svg is being input via stdin. If you would prefer something else, let me know. But I should be able to finish and get a pull request in within the next 1-2 days

**Comment by Angelmmiguel** [comment]
That's great! Thank you.

About the implementation, I didn't investigate so much about handling `stdin` data in nodejs. Ideally, the library should detect if the data comes from the filename parameter or from `stdin`. So, it doesn't need an specific parameter for it.

**Comment by JoshuaAF** [comment]
Sounds good. One more question then. If a user provides a stream to stdin and also provides a filename, what would you like the defined behavior be? I think there are two solutions.

1. Treat it as an error and warn the user to not provide a file via stdin and filename

2. Default to using one over the other

I don't see this situation arising often, but it is an edge case that should be accounted for

**Comment by Angelmmiguel** [comment]
Good question. For this case, I'd prioritize the `STDIN` input over the `filename`. However, if the user is using the `human` formatter (`formatter/human.js`), I'd also add a warning message at the beginning of the output. It only applies to the human formatter because the YAML and JSON output must be valid.
